version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Check if the tag already exist
          command: |
            set +x
            cat /etc/*release
            ls -lha
            echo "GIT_TAG__${GIT_TAG}__"
            . version
            GIT_TAG=2
            git ls-remote --exit-code origin refs/tags/${KAMUS_CLI_VERSION}
            if [[ $? -eq 0 ]]; then
              GIT_TAG="${KAMUS_CLI_VERSION//-*/}-$((${KAMUS_CLI_VERSION//*-/} + 1))"
            else
              GIT_TAG="${KAMUS_CLI_VERSION}-1"
            fi
            echo "export GIT_TAG='123'" >> $BASH_ENV
            echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
      - run:
          name: Create the tag
          command: |
            ls -lha
            echo "GIT_TAG__${GIT_TAG}__"
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}
          
  release:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Tag test
          command: |
            cat /etc/*release
            ls -lha
            cat version || true
            echo "GIT_TAG__${GIT_TAG}__v2"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build