version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Check if the tag already exist
          command: |
            set +e
            . version
            GIT_TAG_LATEST="$(git tag --list | awk '/'${KAMUS_CLI_VERSION//-*/}'/{ a=$1 ; rc = 1 } END{print a ; exit !rc }')"
            if [[ "${KAMUS_CLI_VERSION//-*/}" == "${GIT_TAG_LATEST//-*/}" ]]; then
              GIT_TAG="${GIT_TAG_LATEST//-*/}-$((${GIT_TAG_LATEST//*-/} + 1))"
            else
              GIT_TAG="${KAMUS_CLI_VERSION}"
            fi
            sed -i "s/\(KAMUS_CLI_VERSION\).*/\1=${GIT_TAG}/g" version
            cat version
      - run:
          name: Publish the tag
          command: |
            . version
            git config --global user.email "circleci@lozanomatheus.com"
            git config --global user.name "circleci"
            git add version
            git commit -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}."
            git tag -a ${KAMUS_CLI_VERSION} -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}."
            cat ~/.git-credentials || true
            cat ~/.gitconfig || true
            git push --all --follow-tags
      - add_ssh_keys:
          fingerprints:
            - "a1:c3:96:da:35:9d:23:11:ba:31:de:a3:7f:ba:e5:cd"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
