version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Check if the tag already exist
          command: |
            set +e
            . version
            git ls-remote --exit-code origin refs/tags/${KAMUS_CLI_VERSION}
            if [[ $? -eq 0 ]]; then
              GIT_TAG="${KAMUS_CLI_VERSION//-*/}-$((${KAMUS_CLI_VERSION//*-/} + 1))"
            else
              GIT_TAG="${KAMUS_CLI_VERSION//-*/}-1"
            fi
            sed -i "s/\(KAMUS_CLI_VERSION\).*/\1=${GIT_TAG}/g" version
            cat version
      - run:
          name: Create the tag
          command: |
            . version
            git tag -a ${KAMUS_CLI_VERSION} -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}."
      - run:
          name: Publish the tag
          command: |
            . version
            git push origin ${KAMUS_CLI_VERSION}

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
