version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Check if the tag already exist
          command: |
            ls -lha
            echo "GIT_TAG__${GIT_TAG}__"
            . version
            git ls-remote --exit-code origin refs/tags/${KAMUS_CLI_VERSION}
            if [[ $? -eq 0 ]]; then
              GIT_TAG="${KAMUS_CLI_VERSION//-*/}-$((${KAMUS_CLI_VERSION//*-/} + 1))"
            else
              GIT_TAG="${KAMUS_CLI_VERSION}-1"
            fi
            echo "export GIT_TAG=\"${GIT_TAG}\"" >> $BASH_ENV

      - run:
          name: Create the tag
          command: |
            ls -lha
            echo "GIT_TAG__${GIT_TAG}__"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
