version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Check if the tag already exist
          command: |
            set +e
            set -x
            cat version
            env
            . version
            GIT_TAG_LATEST="$(git tag --sort=creatordate | awk '/'${KAMUS_CLI_VERSION//-*/}'/{ a=$1 ; rc = 1 } END{print a ; exit !rc }')"
            if [[ "${KAMUS_CLI_VERSION//-*/}" == "${GIT_TAG_LATEST//-*/}" ]]; then
              [[ "${GIT_TAG_LATEST}" != *"-"* ]] && GIT_TAG_LATEST=0
              GIT_TAG="${KAMUS_CLI_VERSION//-*/}-$((${GIT_TAG_LATEST//*-/} + 1))"
              echo "aqui__${GIT_TAG}___"
            else
              GIT_TAG="${KAMUS_CLI_VERSION}"
              echo "alis__${GIT_TAG}___"
            fi
            echo "foii__${GIT_TAG}___"
            sed -i "s/\(KAMUS_CLI_VERSION\).*/\1=${GIT_TAG}/g" version
            cat version

      - run:
          name: Publish the tag
          command: |
            set -x
            apk add --no-cache git
            . version
            git config --global user.email "circleci@lozanomatheus.com"
            git config --global user.name "circleci"
            sed -i "s/latest/${KAMUS_CLI_VERSION}/g" README.md
            git add version || true
            git commit -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}." || true
            git push --all
            git add README.md || true
            git commit -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}." || true
            git tag -a ${KAMUS_CLI_VERSION} -m "Releasing Kamus CLI - Version ${KAMUS_CLI_VERSION}."
            git push origin ${KAMUS_CLI_VERSION}

      - add_ssh_keys:
          fingerprints:
            - "a1:c3:96:da:35:9d:23:11:ba:31:de:a3:7f:ba:e5:cd"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
